if(!window.jq||typeof jq!=="function"){var jq=function(g){function w(a,c,b){var d=h.createDocumentFragment();if(b){for(b=a.length-1;b>=0;b--)d.insertBefore(a[b],d.firstChild);c.insertBefore(d,c.firstChild)}else{for(b=0;b<a.length;b++)d.appendChild(a[b]);c.appendChild(d)}}function t(a){return a in u?u[a]:u[a]=RegExp("(^|\\s)"+a+"(\\s|$)")}function p(a){for(var c=0;c<a.length;c++)a.indexOf(a[c])!=c&&(a.splice(c,1),c--);return a}function x(a,c){var b=[];if(a==f)return b;for(;a;a=a.nextSibling)a.nodeType==
1&&a!==c&&b.push(a);return b}function y(a,c){try{return c.querySelectorAll(a)}catch(b){return[]}}function o(){}function z(a,c){a.os={};a.os.webkit=c.match(/WebKit\/([\d.]+)/)?!0:!1;a.os.android=c.match(/(Android)\s+([\d.]+)/)||c.match(/Silk-Accelerated/)?!0:!1;a.os.androidICS=a.os.android&&c.match(/(Android)\s4/)?!0:!1;a.os.ipad=c.match(/(iPad).*OS\s([\d_]+)/)?!0:!1;a.os.iphone=!a.os.ipad&&c.match(/(iPhone\sOS)\s([\d_]+)/)?!0:!1;a.os.webos=c.match(/(webOS|hpwOS)[\s\/]([\d.]+)/)?!0:!1;a.os.touchpad=
a.os.webos&&c.match(/TouchPad/)?!0:!1;a.os.ios=a.os.ipad||a.os.iphone;a.os.ios6=a.os.ios&&c.match(/(OS)\s([6])/)?!0:!1;a.os.playbook=c.match(/PlayBook/)?!0:!1;a.os.blackberry=a.os.playbook||c.match(/BlackBerry/)?!0:!1;a.os.blackberry10=a.os.blackberry&&c.match(/Safari\/536/)?!0:!1;a.os.chrome=c.match(/Chrome/)?!0:!1;a.os.opera=c.match(/Opera Mobi/)?!0:!1;a.os.fennec=c.match(/fennec/i)?!0:!1;a.os.supportsTouch=g.DocumentTouch&&h instanceof g.DocumentTouch||"ontouchstart"in g;a.os.desktop=!(a.os.ios||
a.os.android||a.os.blackberry||a.os.opera||a.os.fennec||a.os.supportsTouch);a.feat={};a.feat.nativeTouchScroll=a.os.ios?!c.match(/OS\s[1-4]/):!1}function q(a){return a._jqmid||(a._jqmid=I++)}function J(a,c,b,d){c=A(c);if(c.ns)var e=RegExp("(?:^| )"+c.ns.replace(" "," .* ?")+"(?: |$)");return(j[q(a)]||[]).filter(function(a){return a&&(!c.e||a.e==c.e)&&(!c.ns||e.test(a.ns))&&(!b||a.fn==b||typeof a.fn==="function"&&typeof b==="function"&&""+a.fn===""+b)&&(!d||a.sel==d)})}function A(a){a=(""+a).split(".");
return{e:a[0],ns:a.slice(1).sort().join(" ")}}function B(a,c,b){e.isObject(a)?e.each(a,b):a.split(/\s/).forEach(function(a){b(a,c)})}function r(a,c,b,d,i){var f=q(a),g=j[f]||(j[f]=[]);B(c,b,function(b,c){var f=i&&i(c,b),l=f||c,h=function(b){var c=l.apply(a,[b].concat(b.data));c===!1&&b.preventDefault();return c},f=e.extend(A(b),{fn:c,proxy:h,sel:d,del:f,i:g.length});g.push(f);a.addEventListener(f.e,h,!1)})}function s(a,c,b,d){var e=q(a);B(c||"",b,function(b,c){J(a,b,c,d).forEach(function(b){delete j[e][b.i];
a.removeEventListener(b.e,b.proxy,!1)})})}function K(a){var c=e.extend({originalEvent:a},a);e.each(L,function(b,d){c[b]=function(){this[d]=M;return a[b].apply(a,arguments)};c[d]=N});return c}function C(a,c){if(c&&a.dispatchEvent){var b=e.Event("destroy",{bubbles:!1});a.dispatchEvent(b)}if((b=q(a))&&j[b]){for(var d in j[b])a.removeEventListener(j[b][d].e,j[b][d].proxy,!1);delete j[b]}}function D(a,c){if(a){var b=a.childNodes;if(b&&b.length>0)for(var d in b)D(b[d],c);C(a,c)}}var f,h=g.document,n=[],
E=n.slice,u=[],O=1,P=/^\s*<(\w+)[^>]*>/,k={},m=function(a,c){this.length=0;if(a)if(a instanceof m&&c==f)return a;else if(e.isFunction(a))return e(h).ready(a);else if(e.isArray(a)&&a.length!=f){for(var b=0;b<a.length;b++)this[this.length++]=a[b];return this}else if(e.isObject(a)&&e.isObject(c)){if(a.length==f)a.parentNode==c&&(this[this.length++]=a);else for(b=0;b<a.length;b++)a[b].parentNode==c&&(this[this.length++]=a[b]);return this}else if(e.isObject(a)&&c==f)return this[this.length++]=a,this;else if(c!==
f){if(c instanceof m)return c.find(a)}else c=h;else return this;if(b=this.selector(a,c))if(e.isArray(b))for(var d=0;d<b.length;d++)this[this.length++]=b[d];else this[this.length++]=b;return this},e=function(a,c){return new m(a,c)};e.is$=function(a){return a instanceof m};e.map=function(a,c){var b,d=[],i;if(e.isArray(a))for(i=0;i<a.length;i++)b=c(a[i],i),b!==f&&d.push(b);else if(e.isObject(a))for(i in a)a.hasOwnProperty(i)&&(b=c(a[i],i),b!==f&&d.push(b));return e([d])};e.each=function(a,c){var b;if(e.isArray(a))for(b=
0;b<a.length;b++){if(c(b,a[b])===!1)break}else if(e.isObject(a))for(b in a)if(a.hasOwnProperty(b)&&c(b,a[b])===!1)break;return a};e.extend=function(a){a==f&&(a=this);if(arguments.length===1){for(var c in a)this[c]=a[c];return this}else E.call(arguments,1).forEach(function(b){for(var c in b)a[c]=b[c]});return a};e.isArray=function(a){return a instanceof Array&&a.push!=f};e.isFunction=function(a){return typeof a==="function"};e.isObject=function(a){return typeof a==="object"};e.fn=m.prototype={constructor:m,
forEach:n.forEach,reduce:n.reduce,push:n.push,indexOf:n.indexOf,concat:n.concat,selector:function(a,c){var b,a=a.trim();a[0]==="#"&&a.indexOf(" ")===-1&&a.indexOf(">")===-1?b=c==h?c.getElementById(a.replace("#","")):[].slice.call(y(a,c)):a[0]==="<"&&a[a.length-1]===">"?(b=h.createElement("div"),b.innerHTML=a.trim(),b=[].slice.call(b.childNodes)):b=[].slice.call(y(a,c));return b},oldElement:f,slice:n.slice,setupOld:function(a){if(a==f)return e();a.oldElement=this;return a},map:function(a){return e.map(this,
function(c,b){return a.call(c,b,c)})},each:function(a){this.forEach(function(c,b){a.call(c,b,c)});return this},ready:function(a){(h.readyState==="complete"||h.readyState==="loaded")&&a();h.addEventListener("DOMContentLoaded",a,!1);return this},find:function(a){if(this.length===0)return f;for(var c=[],b,d=0;d<this.length;d++){b=e(a,this[d]);for(var i=0;i<b.length;i++)c.push(b[i])}return e(p(c))},html:function(a,c){if(this.length===0)return f;if(a===f)return this[0].innerHTML;for(var b=0;b<this.length;b++)c!==
!1&&e.cleanUpContent(this[b],!1,!0),this[b].innerHTML=a;return this},text:function(a){if(this.length===0)return f;if(a===f)return this[0].textContent;for(var c=0;c<this.length;c++)this[c].textContent=a;return this},css:function(a,c,b){b=b!=f?b:this[0];if(this.length===0)return f;if(c==f&&typeof a==="string")return g.getComputedStyle(b),b.style[a]?b.style[a]:g.getComputedStyle(b)[a];for(b=0;b<this.length;b++)if(e.isObject(a))for(var d in a)this[b].style[d]=a[d];else this[b].style[a]=c;return this},
empty:function(){for(var a=0;a<this.length;a++)e.cleanUpContent(this[a],!1,!0),this[a].innerHTML="";return this},hide:function(){if(this.length===0)return this;for(var a=0;a<this.length;a++)if(this.css("display",null,this[a])!="none")this[a].setAttribute("jqmOldStyle",this.css("display",null,this[a])),this[a].style.display="none";return this},show:function(){if(this.length===0)return this;for(var a=0;a<this.length;a++)if(this.css("display",null,this[a])=="none")this[a].style.display=this[a].getAttribute("jqmOldStyle")?
this[a].getAttribute("jqmOldStyle"):"block",this[a].removeAttribute("jqmOldStyle");return this},toggle:function(a){for(var c=a===!0?!0:!1,b=0;b<this.length;b++)g.getComputedStyle(this[b]).display!=="none"||a!==f&&c===!1?(this[b].setAttribute("jqmOldStyle",this[b].style.display),this[b].style.display="none"):(this[b].style.display=this[b].getAttribute("jqmOldStyle")!=f?this[b].getAttribute("jqmOldStyle"):"block",this[b].removeAttribute("jqmOldStyle"));return this},val:function(a){if(this.length===
0)return f;if(a==f)return this[0].value;for(var c=0;c<this.length;c++)this[c].value=a;return this},attr:function(a,c){if(this.length===0)return f;if(c===f&&!e.isObject(a))return this[0].jqmCacheId&&k[this[0].jqmCacheId][a]?this[0].jqmCacheId&&k[this[0].jqmCacheId][a]:this[0].getAttribute(a);for(var b=0;b<this.length;b++)if(e.isObject(a))for(var d in a)e(this[b]).attr(d,a[d]);else if(e.isArray(c)||e.isObject(c)||e.isFunction(c)){if(!this[b].jqmCacheId)this[b].jqmCacheId=e.uuid();k[this[b].jqmCacheId]||
(k[this[b].jqmCacheId]={});k[this[b].jqmCacheId][a]=c}else c==null&&c!==f?(this[b].removeAttribute(a),this[b].jqmCacheId&&k[this[b].jqmCacheId][a]&&delete k[this[b].jqmCacheId][a]):this[b].setAttribute(a,c);return this},removeAttr:function(a){for(var c=this,b=0;b<this.length;b++)a.split(/\s+/g).forEach(function(d){c[b].removeAttribute(d);c[b].jqmCacheId&&k[c[b].jqmCacheId][a]&&delete k[c[b].jqmCacheId][a]});return this},remove:function(a){a=e(this).filter(a);if(a==f)return this;for(var c=0;c<a.length;c++)e.cleanUpContent(a[c],
!0,!0),a[c].parentNode.removeChild(a[c]);return this},addClass:function(a){for(var c=0;c<this.length;c++){var b=this[c].className,d=[],e=this;a.split(/\s+/g).forEach(function(a){e.hasClass(a,e[c])||d.push(a)});this[c].className+=(b?" ":"")+d.join(" ");this[c].className=this[c].className.trim()}return this},removeClass:function(a){for(var c=0;c<this.length;c++){if(a==f){this[c].className="";break}var b=this[c].className;a.split(/\s+/g).forEach(function(a){b=b.replace(t(a)," ")});this[c].className=
b.length>0?b.trim():""}return this},replaceClass:function(a,c){for(var b=0;b<this.length;b++)if(a==f)this[b].className=c;else{var d=this[b].className;a.split(/\s+/g).concat(c.split(/\s+/g)).forEach(function(a){d=d.replace(t(a)," ")});d=d.trim();this[b].className=d.length>0?(d+" "+c).trim():c}return this},hasClass:function(a,c){if(this.length===0)return!1;c||(c=this[0]);return t(a).test(c.className)},append:function(a,c){if(a&&a.length!=f&&a.length===0)return this;if(e.isArray(a)||e.isObject(a))a=
e(a);var b;for(b=0;b<this.length;b++)if(a.length&&typeof a!="string")a=e(a),w(a,this[b],c);else{var d=P.test(a)?e(a):f;if(d==f||d.length==0)d=h.createTextNode(a);d.nodeName!=f&&d.nodeName.toLowerCase()=="script"&&(!d.type||d.type.toLowerCase()==="text/javascript")?g.eval(d.innerHTML):d instanceof m?w(d,this[b],c):c!=f?this[b].insertBefore(d,this[b].firstChild):this[b].appendChild(d)}return this},prepend:function(a){return this.append(a,1)},insertBefore:function(a,c){if(this.length==0)return this;
a=e(a).get(0);if(!a||a.length==0)return this;for(var b=0;b<this.length;b++)c?a.parentNode.insertBefore(this[b],a.nextSibling):a.parentNode.insertBefore(this[b],a);return this},insertAfter:function(a){this.insertBefore(a,!0)},get:function(a){a=a==f?0:a;a<0&&(a+=this.length);return this[a]?this[a]:f},offset:function(){if(this.length===0)return f;var a=this[0].getBoundingClientRect();return{left:a.left+g.pageXOffset,top:a.top+g.pageYOffset,right:a.right+g.pageXOffset,bottom:a.bottom+g.pageYOffset,width:a.right-
a.left,height:a.bottom-a.top}},height:function(){return this.offset().height},width:function(){return this.offset().width},parent:function(a){if(this.length==0)return f;for(var c=[],b=0;b<this.length;b++)this[b].parentNode&&c.push(this[b].parentNode);return this.setupOld(e(p(c)).filter(a))},children:function(a){if(this.length==0)return f;for(var c=[],b=0;b<this.length;b++)c=c.concat(x(this[b].firstChild));return this.setupOld(e(c).filter(a))},siblings:function(a){if(this.length==0)return f;for(var c=
[],b=0;b<this.length;b++)this[b].parentNode&&(c=c.concat(x(this[b].parentNode.firstChild,this[b])));return this.setupOld(e(c).filter(a))},closest:function(a,c){if(this.length==0)return f;var b=this[0],d=e(a,c);if(d.length==0)return e();for(;b&&d.indexOf(b)==-1;)b=b!==c&&b!==h&&b.parentNode;return e(b)},filter:function(a){if(this.length==0)return f;if(a==f)return this;for(var c=[],b=0;b<this.length;b++){var d=this[b];d.parentNode&&e(a,d.parentNode).indexOf(d)>=0&&c.push(d)}return this.setupOld(e(p(c)))},
not:function(a){if(this.length==0)return f;for(var c=[],b=0;b<this.length;b++){var d=this[b];d.parentNode&&e(a,d.parentNode).indexOf(d)==-1&&c.push(d)}return this.setupOld(e(p(c)))},data:function(a,c){return this.attr("data-"+a,c)},end:function(){return this.oldElement!=f?this.oldElement:e()},clone:function(a){a=a===!1?!1:!0;if(this.length==0)return f;for(var c=[],b=0;b<this.length;b++)c.push(this[b].cloneNode(a));return e(c)},size:function(){return this.length},serialize:function(a){if(this.length==
0)return"";for(var c={},b=0;b<this.length;b++)this.slice.call(this[b].elements).forEach(function(a){var b=a.getAttribute("type");if(a.nodeName.toLowerCase()!="fieldset"&&!a.disabled&&b!="submit"&&b!="reset"&&b!="button"&&(b!="radio"&&b!="checkbox"||a.checked))c[a.getAttribute("name")]=a.value});return e.param(c,a)}};var F={type:"GET",beforeSend:o,success:o,error:o,complete:o,context:f,timeout:0,crossDomain:!1};e.jsonP=function(a){var c="jsonp_callback"+ ++O,b="",d=h.createElement("script");g[c]=function(f){clearTimeout(b);
e(d).remove();delete g[c];a.success.call(void 0,f)};d.src=a.url.replace(/=\?/,"="+c);if(a.error)d.onerror=function(){clearTimeout(b);a.error.call(void 0,"","error")};e("head").append(d);a.timeout>0&&(b=setTimeout(function(){a.error.call(void 0,"","timeout")},a.timeout));return{}};e.ajax=function(a){var c;try{var b=a||{},d;for(d in F)b[d]||(b[d]=F[d]);if(!b.url)b.url=g.location;if(!b.contentType)b.contentType="application/x-www-form-urlencoded";if(!b.headers)b.headers={};if(!("async"in b)||b.async!==
!1)b.async=!0;if(b.dataType)switch(b.dataType){case "script":b.dataType="text/javascript, application/javascript";break;case "json":b.dataType="application/json";break;case "xml":b.dataType="application/xml, text/xml";break;case "html":b.dataType="text/html";break;case "text":b.dataType="text/plain";break;default:b.dataType="text/html";break;case "jsonp":return e.jsonP(a)}else b.dataType="text/html";if(e.isObject(b.data))b.data=e.param(b.data);b.type.toLowerCase()==="get"&&b.data&&(b.url+=b.url.indexOf("?")===
-1?"?"+b.data:"&"+b.data);if(/=\?/.test(b.url))return e.jsonP(b);if(!b.crossDomain)b.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(b.url)&&RegExp.$2!=g.location.host;if(!b.crossDomain)b.headers=e.extend({"X-Requested-With":"XMLHttpRequest"},b.headers);var f,l=b.context,h=/^([\w-]+:)\/\//.test(b.url)?RegExp.$1:g.location.protocol;c=new g.XMLHttpRequest;c.onreadystatechange=function(){var a=b.dataType;if(c.readyState===4){clearTimeout(f);var d,e=!1;if(c.status>=200&&c.status<300||c.status===0&&h=="file:"){if(a===
"application/json"&&!/^\s*$/.test(c.responseText))try{d=JSON.parse(c.responseText)}catch(g){e=g}else d=c.responseText;c.status===0&&d.length===0&&(e=!0);e?b.error.call(l,c,"parsererror",e):b.success.call(l,d,"success",c)}else e=!0,b.error.call(l,c,"error");b.complete.call(l,c,e?"error":"success")}};c.open(b.type,b.url,b.async);if(b.withCredentials)c.withCredentials=!0;if(b.contentType)b.headers["Content-Type"]=b.contentType;for(var j in b.headers)c.setRequestHeader(j,b.headers[j]);if(b.beforeSend.call(l,
c,b)===!1)return c.abort(),!1;b.timeout>0&&(f=setTimeout(function(){c.onreadystatechange=o;c.abort();b.error.call(l,c,"timeout")},b.timeout));c.send(b.data)}catch(k){console.log(k)}return c};e.get=function(a,c){return this.ajax({url:a,success:c})};e.post=function(a,c,b,d){typeof c==="function"&&(b=c,c={});d===f&&(d="html");return this.ajax({url:a,type:"POST",data:c,dataType:d,success:b})};e.getJSON=function(a,c,b){typeof c==="function"&&(b=c,c={});return this.ajax({url:a,data:c,success:b,dataType:"json"})};
e.param=function(a,c){var b=[];if(a instanceof m)a.each(function(){b.push((c?c+"[]":this.id)+"="+encodeURIComponent(this.value))});else for(var d in a){var f=c?c+"["+d+"]":d,g=a[d];b.push(e.isObject(g)?e.param(g,f):f+"="+encodeURIComponent(g))}return b.join("&")};e.parseJSON=function(a){return JSON.parse(a)};e.parseXML=function(a){return(new DOMParser).parseFromString(a,"text/xml")};z(e,navigator.userAgent);e.__detectUA=z;if(typeof String.prototype.trim!=="function")String.prototype.trim=function(){this.replace(/(\r\n|\n|\r)/gm,
"").replace(/^\s+|\s+$/,"");return this};e.uuid=function(){var a=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()};var j={},I=1,Q={};e.event={add:r,remove:s};e.fn.bind=function(a,c){for(var b=0;b<this.length;b++)r(this[b],a,c);return this};e.fn.unbind=function(a,c){for(var b=0;b<this.length;b++)s(this[b],a,c);return this};e.fn.one=function(a,c){return this.each(function(b,d){r(this,a,c,null,function(a,b){return function(){var c=
a.apply(d,arguments);s(d,b,a);return c}})})};var M=function(){return!0},N=function(){return!1},L={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};e.fn.delegate=function(a,c,b){for(var d=0;d<this.length;d++){var f=this[d];r(f,c,b,a,function(b){return function(c){var d,g=e(c.target).closest(a,f).get(0);if(g)return d=e.extend(K(c),{currentTarget:g,liveFired:f}),b.apply(g,[d].concat([].slice.call(arguments,1)))}})}return this};
e.fn.undelegate=function(a,c,b){for(var d=0;d<this.length;d++)s(this[d],c,b,a);return this};e.fn.on=function(a,c,b){return c===f||e.isFunction(c)?this.bind(a,c):this.delegate(c,a,b)};e.fn.off=function(a,c,b){return c===f||e.isFunction(c)?this.unbind(a,c):this.undelegate(c,a,b)};e.fn.trigger=function(a,c,b){typeof a=="string"&&(a=e.Event(a,b));a.data=c;for(c=0;c<this.length;c++)this[c].dispatchEvent(a);return this};e.Event=function(a,c){var b=h.createEvent(Q[a]||"Events"),d=!0;if(c)for(var e in c)e==
"bubbles"?d=!!c[e]:b[e]=c[e];b.initEvent(a,d,!0,null,null,null,null,null,null,null,null,null,null,null,null);return b};e.bind=function(a,c,b){if(!a.__events)a.__events={};e.isArray(c)||(c=[c]);for(var d=0;d<c.length;d++)a.__events[c[d]]||(a.__events[c[d]]=[]),a.__events[c[d]].push(b)};e.trigger=function(a,c,b){var d=!0;if(!a.__events)return d;e.isArray(c)||(c=[c]);e.isArray(b)||(b=[]);for(var f=0;f<c.length;f++)if(a.__events[c[f]])for(var g=a.__events[c[f]],h=0;h<g.length;h++)e.isFunction(g[h])&&
g[h].apply({},b)===!1&&(d=!1);return d};e.unbind=function(a,c,b){if(!a.__events)return ret;e.isArray(c)||(c=[c]);for(var d=0;d<c.length;d++)if(a.__events[c[d]])for(var f=a.__events[c[d]],g=0;g<f.length;g++)if(f[g]==b){f.splice(g,1);break}};e.proxy=function(a,c,b){return function(){if(b)return a.apply(c,b);return a.apply(c,arguments)}};var R=function(a,c){for(var b=0;b<a.length;b++)D(a[b],c)};e.cleanUpContent=function(a,c,b){if(a){var d=a.childNodes;d&&d.length>0&&e.asap(R,{},[E.apply(d,[0]),b]);c&&
C(a,b)}};var v=[],G=[],H=[];e.asap=function(a,c,b){if(!e.isFunction(a))throw"$.asap - argument is not a valid function";v.push(a);G.push(c?c:{});H.push(b?b:[]);g.postMessage("jqm-asap","*")};g.addEventListener("message",function(a){a.source==g&&a.data=="jqm-asap"&&(a.stopPropagation(),v.length>0&&v.shift().apply(G.shift(),H.shift()))},!0);return e}(window);"$"in window||(window.$=jq);if(!window.numOnly)window.numOnly=function(g){if(g===void 0||g==="")return 0;if(isNaN(parseFloat(g)))if(g.replace)g=
g.replace(/[^0-9.-]/,"");else return 0;return parseFloat(g)}};
(function(e){var h=[],k=function(b,a){var c,f;c=typeof b=="string"||b instanceof String?document.getElementById(b):e.is$(b)?b[0]:b;if(!c.jqmCSS3AnimateId)c.jqmCSS3AnimateId=e.uuid();f=c.jqmCSS3AnimateId;h[f]?(h[f].animate(a),c=h[f]):(c=i(c,a),h[f]=c);return c};e.fn.css3Animate=function(b){if(!b.complete&&b.callback)b.complete=b.callback;var a=k(this[0],b);b.complete=null;b.sucess=null;b.failure=null;for(var c=1;c<this.length;c++)a.link(this[c],b);return a};e.css3AnimateQueue=function(){return new i.queue};
if(window.WebKitCSSMatrix){var l="m11"in new WebKitCSSMatrix?"3d(":"(",m="m11"in new WebKitCSSMatrix?",0)":")",i=function(){var b=function(a,c){if(!(this instanceof b))return new b(a,c);this.callbacksStack=[];this.activeEvent=null;this.countStack=0;this.isActive=!1;this.el=a;this.linkFinishedProxy_=e.proxy(this.linkFinished,this);if(this.el){this.animate(c);var f=this;jq(this.el).bind("destroy",function(){var a=f.el.jqmCSS3AnimateId;f.callbacksStack=[];h[a]&&delete h[a]})}};b.prototype={animate:function(a){this.isActive&&
this.cancel();this.isActive=!0;if(a){var c=!!a.addClass;if(c)a.removeClass?jq(this.el).replaceClass(a.removeClass,a.addClass):jq(this.el).addClass(a.addClass);else{var b=numOnly(a.time);b==0&&(a.time=0);a.y||(a.y=0);a.x||(a.x=0);if(a.previous){var d=new WebKitCSSMatrix(window.getComputedStyle(this.el).webkitTransform);a.y+=numOnly(d.f);a.x+=numOnly(d.e)}if(!a.origin)a.origin="0% 0%";if(!a.scale)a.scale="1";if(!a.rotateY)a.rotateY="0";if(!a.rotateX)a.rotateX="0";if(!a.skewY)a.skewY="0";if(!a.skewX)a.skewX=
"0";a.timingFunction||(a.timingFunction="linear");if(typeof a.x=="number"||a.x.indexOf("%")==-1&&a.x.toLowerCase().indexOf("px")==-1&&a.x.toLowerCase().indexOf("deg")==-1)a.x=parseInt(a.x)+"px";if(typeof a.y=="number"||a.y.indexOf("%")==-1&&a.y.toLowerCase().indexOf("px")==-1&&a.y.toLowerCase().indexOf("deg")==-1)a.y=parseInt(a.y)+"px";this.el.style.webkitTransform="translate"+l+a.x+","+a.y+m+" scale("+parseFloat(a.scale)+") rotate("+a.rotateX+") rotateY("+a.rotateY+") skew("+a.skewX+","+a.skewY+
")";this.el.style.webkitBackfaceVisiblity="hidden";d="-webkit-transform";if(a.opacity!==void 0)this.el.style.opacity=a.opacity,d+=", opacity";if(a.width)this.el.style.width=a.width,d="all";if(a.height)this.el.style.height=a.height,d="all";this.el.style.webkitTransitionProperty=d;if((""+a.time).indexOf("s")===-1)var d="ms",j=a.time+d;else a.time.indexOf("ms")!==-1?(d="ms",j=a.time):(d="s",j=a.time+d);this.el.style.webkitTransitionDuration=j;this.el.style.webkitTransitionTimingFunction=a.timingFunction;
this.el.style.webkitTransformOrigin=a.origin}this.callbacksStack.push({complete:a.complete,success:a.success,failure:a.failure});this.countStack++;var g=this,a=window.getComputedStyle(this.el);if(c)c=a.webkitTransitionDuration,b=numOnly(c),d=c.indexOf("ms")!==-1?"ms":"s";b==0||d=="ms"&&b<5||a.display=="none"?e.asap(e.proxy(this.finishAnimation,this,[!1])):(this.activeEvent=function(a){g.finishAnimation(a);g.el.removeEventListener("webkitTransitionEnd",g.activeEvent,!1)},this.el.addEventListener("webkitTransitionEnd",
this.activeEvent,!1))}else alert("Please provide configuration options for animation of "+this.el.id)},addCallbackHook:function(a){a&&this.callbacksStack.push(a);this.countStack++;return this.linkFinishedProxy_},linkFinished:function(a){a?this.cancel():this.finishAnimation()},finishAnimation:function(a){a&&a.preventDefault();this.isActive&&(this.countStack--,this.countStack==0&&this.fireCallbacks(!1))},fireCallbacks:function(a){this.clearEvents();var c=this.callbacksStack;this.cleanup();for(var b=
0;b<c.length;b++){var d=c[b].complete,e=c[b].success,g=c[b].failure;d&&typeof d=="function"&&d(a);a&&g&&typeof g=="function"?g():e&&typeof e=="function"&&e()}},cancel:function(){this.isActive&&this.fireCallbacks(!0)},cleanup:function(){this.callbacksStack=[];this.isActive=!1;this.countStack=0},clearEvents:function(){this.activeEvent&&this.el.removeEventListener("webkitTransitionEnd",this.activeEvent,!1);this.activeEvent=null},link:function(a,c){var b={complete:c.complete,success:c.success,failure:c.failure};
c.complete=this.addCallbackHook(b);c.success=null;c.failure=null;k(a,c);c.complete=b.complete;c.success=b.success;c.failure=b.failure;return this}};return b}();i.queue=function(){return{elements:[],push:function(b){this.elements.push(b)},pop:function(){return this.elements.pop()},run:function(){var b=this;if(this.elements.length!=0&&(typeof this.elements[0]=="function"&&this.shift()(),this.elements.length!=0)){var a=this.shift();if(this.elements.length>0)a.complete=function(a){a||b.run()};i(document.getElementById(a.id),
a)}},shift:function(){return this.elements.shift()}}}}})(jq);
(function(d){var c=[];d.fn.swipeListener=function(b){if(b===void 0&&this.length>0)return c[this[0].id]?c[this[0].id]:null;for(var a=0;a<this.length;a++)tmp=new e(this[a],b),this[a].id&&(c[this[a].id]=tmp);return this.length==1?tmp:this};var e=function(){var b=function(a,b){var c=this;if(this.el=typeof a=="string"?document.getElementById(a):a)for(j in this.el.addEventListener("touchmove",function(a){c.touchMove(a)},!1),this.el.addEventListener("touchend",function(a){c.touchEnd(a)},!1),b)this[j]=b[j];
else alert("Error adding swipe listener for "+a)};b.prototype={startX:0,startY:0,movingX:0,movingY:0,vthreshold:50,hthreshold:50,movingElement:!1,swipeDirection:{up:!1,down:!1,left:!1,right:!1},callBack:null,cancel:function(){this.movingY=this.movingX=this.startY=this.startX=0;this.movingElement=!1;this.swipeDirection={up:!1,down:!1,left:!1,right:!1}},touchStart:function(a){if(!(a.touches[0].target&&a.touches[0].target.type!=void 0)&&a.touches.length==1)this.movingElement=!0,this.startX=a.touches[0].pageX,
this.startY=a.touches[0].pageY,a.preventDefault()},touchMove:function(a){this.movingElement==!1&&this.touchStart(a);a.preventDefault();a.touches.length>1||!this.movingElement?this.cancel():(this.movingX=a.touches[0].pageX-this.startX,this.movingY=a.touches[0].pageY-this.startY)},touchEnd:function(a){if(this.movingElement){a.preventDefault();a=!1;if(Math.abs(this.movingX)>this.hthreshold)this.swipeDirection.right=this.movingX>0,this.swipeDirection.left=this.movingX<0,a=!0;if(Math.abs(this.movingY)>
this.vthreshold)this.swipeDirection.up=this.movingY<0,this.swipeDirection.down=this.movingY>0,a=!0;a&&typeof(this.callBack=="function")&&this.callBack(this.swipeDirection);this.cancel()}}};return b}()})(jq);
(function(j){var i=[];j.fn.carousel=function(h){for(var f,g,a=0;a<this.length;a++){f=this[a];if(!f.jqmCarouselId)f.jqmCarouselId=j.uuid();g=f.jqmCarouselId;i[g]?f=i[g]:(f=new l(this[a],h),i[g]=f)}return this.length==1?f:this};var l=function(){if(window.WebKitCSSMatrix){var h="m11"in new WebKitCSSMatrix?"3d(":"(",f="m11"in new WebKitCSSMatrix?",0)":")",g=function(a,c){if(this.container=typeof a==="string"||a instanceof String?document.getElementById(a):a){if(this instanceof g)for(var b in c)c.hasOwnProperty(b)&&
(this[b]=c[b]);else return new g(a,c);var d=this;jq(this.container).bind("destroy",function(){var a=d.container.jqmCarouselId;window.removeEventListener("orientationchange",d.orientationHandler,!1);i[a]&&delete i[a]});this.pagingDiv=this.pagingDiv?document.getElementById(this.pagingDiv):null;this.container.style.overflow="hidden";this.container.style["-webkit-box-orient"]="vertical";this.container.style.display="-webkit-box";this.container.style["-webkit-box-orient"]="vertical";if(this.vertical)this.horizontal=
!1;b=document.createElement("div");this.container.appendChild(b);for(var e=j(b),f=j(this.container),h=Array.prototype.slice.call(this.container.childNodes);h.length>0;){var k=h.splice(0,1),k=f.find(k);k.get()!=b&&e.append(k.get())}this.horizontal?(b.style.display="-webkit-box",b.style["-webkit-box-flex"]=1):b.style.display="block";this.el=b;this.refreshItems();b=jq(b);b.bind("touchmove",function(a){d.touchMove(a)});b.bind("touchend",function(a){d.touchEnd(a)});b.bind("touchstart",function(a){d.touchStart(a)});
this.orientationHandler=function(){d.onMoveIndex(d.carouselIndex,0)};window.addEventListener("orientationchange",this.orientationHandler,!1)}else alert("Error finding container for carousel "+a)};g.prototype={startX:0,startY:0,dx:0,dy:0,myDivWidth:0,myDivHeight:0,cssMoveStart:0,childrenCount:0,carouselIndex:0,vertical:!1,horizontal:!0,el:null,movingElement:!1,container:null,pagingDiv:null,pagingCssName:"carousel_paging",pagingCssNameSelected:"carousel_paging_selected",pagingFunction:null,lockMove:!1,
touchStart:function(a){this.myDivWidth=numOnly(this.container.clientWidth);this.myDivHeight=numOnly(this.container.clientHeight);this.lockMove=!1;if(event.touches[0].target&&event.touches[0].target.type!==void 0){var c=event.touches[0].target.tagName.toLowerCase();if(c==="select"||c==="input"||c==="button")return}if(a.touches.length===1)if(this.movingElement=!0,this.startY=a.touches[0].pageY,this.startX=a.touches[0].pageX,this.vertical)try{this.cssMoveStart=numOnly((new WebKitCSSMatrix(window.getComputedStyle(this.el,
null).webkitTransform)).f)}catch(b){this.cssMoveStart=0}else try{this.cssMoveStart=numOnly((new WebKitCSSMatrix(window.getComputedStyle(this.el,null).webkitTransform)).e)}catch(d){this.cssMoveStart=0}},touchMove:function(a){if(this.movingElement){if(a.touches.length>1)return this.touchEnd(a);var c={x:a.touches[0].pageX-this.startX,y:a.touches[0].pageY-this.startY};if(this.vertical)c={x:0,y:0},this.dy=a.touches[0].pageY-this.startY,this.dy+=this.cssMoveStart,c.y=this.dy,a.preventDefault();else{var b;
if(b=!this.lockMove)c=Math.round(Math.atan2(c.y,c.x)*180/Math.PI),c<0&&(c=360-Math.abs(c)),b=c<=215&&c>=155||c<=45&&c>=0||c<=360&&c>=315?!0:!1;if(b)c={x:0,y:0},this.dx=a.touches[0].pageX-this.startX,this.dx+=this.cssMoveStart,a.preventDefault(),c.x=this.dx;else return this.lockMove=!0}c&&this.moveCSS3(this.el,c)}},touchEnd:function(){if(this.movingElement){var a=!1;try{var c=this.vertical?numOnly((new WebKitCSSMatrix(window.getComputedStyle(this.el,null).webkitTransform)).f):numOnly((new WebKitCSSMatrix(window.getComputedStyle(this.el,
null).webkitTransform)).e);if(c>0)this.moveCSS3(this.el,{x:0,y:0},"300");else{var b=this.vertical?this.dy%this.myDivHeight/this.myDivHeight*-100:this.dx%this.myDivWidth/this.myDivWidth*-100,d=this.carouselIndex;c<this.cssMoveStart&&b>3?d++:c>this.cssMoveStart&&b<97&&d--;d>this.childrenCount-1&&(d=this.childrenCount-1);d<0&&(d=0);c={x:0,y:0};this.vertical?c.y=d*this.myDivHeight*-1:c.x=d*this.myDivWidth*-1;this.moveCSS3(this.el,c,"150");if(this.pagingDiv&&this.carouselIndex!==d)document.getElementById(this.container.id+
"_"+this.carouselIndex).className=this.pagingCssName,document.getElementById(this.container.id+"_"+d).className=this.pagingCssNameSelected;this.carouselIndex!=d&&(a=!0);this.carouselIndex=d}}catch(e){console.log(e)}this.dx=0;this.movingElement=!1;this.startY=this.dy=this.startX=0;a&&this.pagingFunction&&typeof this.pagingFunction=="function"&&this.pagingFunction(this.carouselIndex)}},onMoveIndex:function(a,c){this.myDivWidth=numOnly(this.container.clientWidth);this.myDivHeight=numOnly(this.container.clientHeight);
var b=!1;if(document.getElementById(this.container.id+"_"+this.carouselIndex))document.getElementById(this.container.id+"_"+this.carouselIndex).className=this.pagingCssName;var d=Math.abs(a-this.carouselIndex),e=a;e<0&&(e=0);e>this.childrenCount-1&&(e=this.childrenCount-1);var f={x:0,y:0};this.vertical?f.y=e*this.myDivHeight*-1:f.x=e*this.myDivWidth*-1;d=c?c:50+parseInt(d*20);this.moveCSS3(this.el,f,d);this.carouselIndex!=e&&(b=!0);this.carouselIndex=e;if(this.pagingDiv&&(e=document.getElementById(this.container.id+
"_"+this.carouselIndex)))e.className=this.pagingCssNameSelected;b&&this.pagingFunction&&typeof this.pagingFunction=="function"&&this.pagingFunction(currInd)},moveCSS3:function(a,c,b,d){b=b?parseInt(b):0;d||(d="linear");a.style.webkitTransform="translate"+h+c.x+"px,"+c.y+"px"+f;a.style.webkitTransitionDuration=b+"ms";a.style.webkitBackfaceVisiblity="hidden";a.style.webkitTransformStyle="preserve-3d";a.style.webkitTransitionTimingFunction=d},addItem:function(a){a&&a.nodeType&&(this.container.childNodes[0].appendChild(a),
this.refreshItems())},refreshItems:function(){var a=0,c=this,b=this.el;n=b.childNodes[0];for(var d,e=[];n;n=n.nextSibling)n.nodeType===1&&(e.push(n),a++);this.childrenCount=a;d=parseFloat(100/this.childrenCount)+"%";for(a=0;a<e.length;a++)this.horizontal?(e[a].style.width=d,e[a].style.height="100%"):(e[a].style.height=d,e[a].style.width="100%",e[a].style.display="block");this.moveCSS3(b,{x:0,y:0});this.horizontal?(b.style.width=Math.ceil(this.childrenCount*100)+"%",b.style.height="100%",b.style["min-height"]=
"100%"):(b.style.width="100%",b.style.height=Math.ceil(this.childrenCount*100)+"%",b.style["min-height"]=Math.ceil(this.childrenCount*100)+"%");if(this.pagingDiv){this.pagingDiv.innerHTML="";for(a=0;a<this.childrenCount;a++)b=document.createElement("div"),b.id=this.container.id+"_"+a,b.pageId=a,b.className=a!==this.carouselIndex?this.pagingCssName:this.pagingCssNameSelected,b.onclick=function(){c.onMoveIndex(this.pageId)},e=document.createElement("div"),e.style.width="20px",this.horizontal?(e.style.cssFloat=
"left",e.innerHTML="&nbsp;"):(e.innerHTML="&nbsp;",e.style.display="block"),this.pagingDiv.appendChild(b),a+1<this.childrenCount&&this.pagingDiv.appendChild(e),e=b=null;this.pagingDiv.style.width=this.childrenCount*50+"px";this.pagingDiv.style.height="25px"}this.onMoveIndex(this.carouselIndex)}};return g}}()})(jq);
(function(e){function m(e){if(!h[e].el)return delete h[e],!1;return!0}function o(){if(jq.os.android&&!jq.os.chrome){var i=!1;e.bind(e.touchLayer,"pre-enter-edit",function(e){if(!i)for(el in i=!0,h)m(el)&&h[el].needsFormsFix(e)&&h[el].startFormsMode()});e.bind(e.touchLayer,["cancel-enter-edit","exit-edit"],function(){if(i)for(el in i=!1,h)m(el)&&h[el].androidFormsMode&&h[el].stopFormsMode()})}n=!0}var h=[];e.fn.scroller=function(i){for(var g,k,l=0;l<this.length;l++){g=this[l];if(!g.jqmScrollerId)g.jqmScrollerId=
e.uuid();k=g.jqmScrollerId;if(h[k])g=h[k];else{i||(i={});if(!e.feat.nativeTouchScroll)i.useJsScroll=!0;g=p(this[l],i);h[k]=g}}return this.length==1?g:this};var n=!1,p=function(){function i(a,b){var c=document.createElement("div");c.style.position="absolute";c.style.width=a+"px";c.style.height=b+"px";c.style.webkitBorderRadius="2px";c.style.opacity=0;c.className="scrollBar";c.style.background="black";return c}if(window.WebKitCSSMatrix){var g="m11"in new WebKitCSSMatrix,k=g?"3d(":"(",l=g?",0)":")",
d,f,g=function(){};g.prototype={refresh:!1,refreshHangTimeout:2E3,refreshHeight:60,refreshElement:null,refreshCancelCB:null,refreshRunning:!1,scrollTop:0,scrollLeft:0,preventHideRefresh:!0,verticalScroll:!0,horizontalScroll:!1,refreshTriggered:!1,moved:!1,eventsActive:!1,rememberEventsActive:!1,scrollingLocked:!1,autoEnable:!0,blockFormsFix:!1,loggedPcentY:0,loggedPcentX:0,init:function(a,b){this.el=a;this.jqEl=e(this.el);this.defaultProperties();for(j in b)this[j]=b[j];var c=this,d=function(){c.eventsActive&&
c.adjustScroll()};this.jqEl.bind("destroy",function(){c.disable(!0);var a=c.el.jqmScrollerId;h[a]&&delete h[a];e.unbind(e.touchLayer,"orientationchange-reshape",d)});e.bind(e.touchLayer,"orientationchange-reshape",d)},needsFormsFix:function(a){return this.useJsScroll&&this.isEnabled()&&this.el.style.display!="none"&&e(a).closest(this.jqEl).size()>0},handleEvent:function(a){if(!this.scrollingLocked)switch(a.type){case "touchstart":this.preventHideRefresh=!this.refreshRunning;this.moved=!1;this.onTouchStart(a);
break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a);break;case "scroll":this.onScroll(a)}},coreAddPullToRefresh:function(a){if(a)this.refreshElement=a;this.refreshElement==null?(a=document.getElementById(this.container.id+"_pulldown"),a=a!=null?jq(a):jq("<div id='"+this.container.id+"_pulldown' class='jqscroll_refresh' style='border-radius:.6em;border: 1px solid #2A2A2A;background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0,#666666),color-stop(1,#222222));background:#222222;margin:0px;height:60px;position:relative;text-align:center;line-height:60px;color:white;width:100%;'>Pull to Refresh</div>")):
a=jq(this.refreshElement);a=a.get();this.refreshContainer=jq('<div style="overflow:hidden;width:100%;height:0;margin:0;padding:0;padding-left:5px;padding-right:5px;"></div>');e(this.el).prepend(this.refreshContainer.append(a,"top"));this.refreshContainer=this.refreshContainer[0]},fireRefreshRelease:function(a,b){if(this.refresh){var c=e.trigger(this,"refresh-release",[a])!==!1;this.preventHideRefresh=!1;this.refreshRunning=!0;if(a){if(c){var d=this;if(this.refreshHangTimeout>0)this.refreshCancelCB=
setTimeout(function(){d.hideRefresh()},this.refreshHangTimeout)}}else b&&this.hideRefresh()}},lock:function(){if(!this.scrollingLocked)this.scrollingLocked=!0,(this.rememberEventsActive=this.eventsActive)||this.initEvents()},unlock:function(){if(this.scrollingLocked)this.scrollingLocked=!1,this.rememberEventsActive||this.removeEvents()},scrollToItem:function(a,b){e.is$(a)||(a=e(a));if(b=="bottom"){var c=a.offset(),c=c.top-this.jqEl.offset().bottom+c.height;c+=4}else{var c=a.offset().top-document.body.scrollTop,
d=this.jqEl.offset().top;document.body.scrollTop<d&&(c-=d);c-=4}this.scrollBy({y:c,x:0},0)},setPaddings:function(a,b){var c=e(this.el),d=numOnly(c.css("paddingTop"));c.css("paddingTop",a+"px").css("paddingBottom",b+"px");this.scrollBy({y:a-d,x:0})},divide:function(a,b){return b!=0?a/b:0},isEnabled:function(){return this.eventsActive}};d=function(a,b){this.init(a,b);this.container=this.el.parentNode;this.container.jqmScrollerId=a.jqmScrollerId;this.jqEl=e(this.container);if(this.container.style.overflow!=
"hidden"&&this.container.style.overflow!="visible")this.container.style.overflow="hidden";this.addPullToRefresh(null,!0);this.autoEnable&&this.enable(!0);if(this.verticalScroll&&this.verticalScroll==!0&&this.scrollBars==!0){var c=i(5,20);c.style.top="0px";if(this.vScrollCSS)c.className=this.vScrollCSS;c.style.opacity="0";this.container.appendChild(c);this.vscrollBar=c}if(this.horizontalScroll&&this.horizontalScroll==!0&&this.scrollBars==!0){c=i(20,5);c.style.bottom="0px";if(this.hScrollCSS)c.className=
this.hScrollCSS;c.style.opacity="0";this.container.appendChild(c);this.hscrollBar=c}this.horizontalScroll&&(this.el.style["float"]="left");this.el.hasScroller=!0};f=function(a,b){this.init(a,b);this.container=this.el;this.addPullToRefresh(null,!0);this.autoEnable&&this.enable()};f.prototype=new g;d.prototype=new g;f.prototype.defaultProperties=function(){this.refreshContainer=null;this.dY=this.cY=0;this.cancelPropagation=!1;this.loggedPcentX=this.loggedPcentY=0;var a=this;this.adjustScrollOverflowProxy_=
function(){a.jqEl.css("overflow","auto")}};f.prototype.enable=function(a){if(!this.eventsActive)this.eventsActive=!0,this.el.style.overflow="auto",a||this.adjustScroll(),this.refresh&&this.el.addEventListener("touchstart",this,!1),this.el.addEventListener("scroll",this,!1)};f.prototype.disable=function(a){if(this.eventsActive){this.logPos(this.el.scrollLeft,this.el.scrollTop);if(!a)this.el.style.overflow="hidden";this.el.removeEventListener("touchstart",this,!1);this.el.removeEventListener("scroll",
this,!1);this.eventsActive=!1}};f.prototype.addPullToRefresh=function(a,b){if(!b)this.refresh=!0;this.refresh&&this.refresh==!0&&this.coreAddPullToRefresh(a)};f.prototype.onTouchStart=function(a){this.refreshCancelCB&&clearTimeout(this.refreshCancelCB);if(this.refresh&&this.el.scrollTop==0)this.refreshHeight=this.refreshContainer.firstChild.clientHeight,this.el.addEventListener("touchmove",this,!1),this.dY=a.touches[0].pageY};f.prototype.onTouchMove=function(a){a=a.touches[0].pageY-this.dY;if(!this.moved&&
a<0)this.el.removeEventListener("touchmove",this,!1),this.el.removeEventListener("touchend",this,!1);else{if(!this.moved&&a>0)this.scrollTo({y:this.refreshHeight,x:this.scrollLeft}),this.refreshContainer.style.height=this.refreshHeight+"px",this.el.addEventListener("touchend",this,!1),this.moved=!0;var b=a-this.cY;if(!this.refreshTriggered&&this.scrollTop-b<=0)this.refreshTriggered=!0,e.trigger(this,"refresh-trigger");else if(this.refreshTriggered&&this.scrollTop-b>0)this.refreshTriggered=!1,e.trigger(this,
"refresh-cancel");this.cY=a}};f.prototype.onTouchEnd=function(){this.fireRefreshRelease(this.el.scrollTop<=0,!0);this.dY=this.cY=0;this.el.removeEventListener("touchmove",this,!1);this.el.removeEventListener("touchend",this,!1)};f.prototype.hideRefresh=function(a){if(!this.preventHideRefresh){var b=this,c=function(a){if(!a)b.el.style.webkitTransform="none",b.el.style.webkitTransitionProperty="none",b.el.scrollTop=0,b.logPos(b.el.scrollLeft,0);b.refreshContainer.style.height="0";b.dY=b.cY=0};a===!1?
c():b.jqEl.css3Animate({y:b.el.scrollTop-b.refreshHeight+"px",x:"0%",time:"75ms",complete:c});this.refreshTriggered=!1}};f.prototype.hideScrollbars=function(){};f.prototype.scrollTo=function(a){this.el.scrollTop=-a.y;this.el.scrollLeft=-a.x;this.logPos(this.el.scrollLeft,this.el.scrollTop)};f.prototype.scrollBy=function(a){this.el.scrollTop+=a.y;this.el.scrollLeft+=a.x;this.logPos(this.el.scrollLeft,this.el.scrollTop)};f.prototype.onScroll=function(){this.logPos(this.el.scrollLeft,this.el.scrollTop)};
f.prototype.logPos=function(a,b){this.loggedPcentX=this.divide(a,this.el.scrollWidth-this.el.clientWidth);this.loggedPcentY=this.divide(b,this.el.scrollHeight-this.el.clientHeight);this.scrollLeft=a;this.scrollTop=b};f.prototype.adjustScroll=function(){this.jqEl.css("overflow","hidden");this.el.scrollLeft=this.loggedPcentX*(this.el.scrollWidth-this.el.clientWidth);this.el.scrollTop=this.loggedPcentY*(this.el.scrollHeight-this.el.clientHeight);this.logPos(this.el.scrollLeft,this.el.scrollTop);e.asap(this.adjustScrollOverflowProxy_)};
d.prototype.defaultProperties=function(){this.boolScrollLock=!1;this.elementInfo=this.currentScrollingObject=null;this.verticalScroll=!0;this.horizontalScroll=!1;this.scrollBars=!0;this.hscrollBar=this.vscrollBar=null;this.vScrollCSS=this.hScrollCSS="scrollBar";this.firstEventInfo=null;this.moved=!1;this.preventPullToRefresh=!0;this.doScrollInterval=null;this.refreshRate=25;this.refreshSafeKeep=this.androidFormsMode=this.isScrolling=!1;this.lastScrollbar="";this.scrollingFinishCB=this.container=this.finishScrollingObject=
null;this.loggedPcentX=this.loggedPcentY=0};d.prototype.enable=function(a){if(!this.eventsActive)this.eventsActive=!0,a||this.adjustScroll(),this.container.addEventListener("touchstart",this,!1),this.container.addEventListener("touchmove",this,!1),this.container.addEventListener("touchend",this,!1)};d.prototype.adjustScroll=function(){var a=this.getViewportSize();this.scrollerMoveCSS({x:Math.round(this.loggedPcentX*(this.el.clientWidth-a.w)),y:Math.round(this.loggedPcentY*(this.el.clientHeight-a.h))},
0)};d.prototype.disable=function(){if(this.eventsActive){var a=this.getCSSMatrix(this.el);this.logPos(numOnly(a.e)-numOnly(this.container.scrollLeft),numOnly(a.f)-numOnly(this.container.scrollTop));this.container.removeEventListener("touchstart",this,!1);this.container.removeEventListener("touchmove",this,!1);this.container.removeEventListener("touchend",this,!1);this.eventsActive=!1}};d.prototype.addPullToRefresh=function(a,b){if(!b)this.refresh=!0;if(this.refresh&&this.refresh==!0)this.coreAddPullToRefresh(a),
this.el.style.overflow="visible"};d.prototype.hideScrollbars=function(){if(this.hscrollBar)this.hscrollBar.style.opacity=0,this.hscrollBar.style.webkitTransitionDuration="0ms";if(this.vscrollBar)this.vscrollBar.style.opacity=0,this.vscrollBar.style.webkitTransitionDuration="0ms"};d.prototype.getViewportSize=function(){var a=window.getComputedStyle(this.container);isNaN(numOnly(a.paddingTop))&&alert(typeof a.paddingTop+"::"+a.paddingTop+":");return{h:this.container.clientHeight>window.innerHeight?
window.innerHeight:this.container.clientHeight-numOnly(a.paddingTop)-numOnly(a.paddingBottom),w:this.container.clientWidth>window.innerWidth?window.innerWidth:this.container.clientWidth-numOnly(a.paddingLeft)-numOnly(a.paddingRight)}};d.prototype.onTouchStart=function(a){this.moved=!1;this.currentScrollingObject=null;if(this.container){if(this.refreshCancelCB)clearTimeout(this.refreshCancelCB),this.refreshCancelCB=null;if(this.scrollingFinishCB)clearTimeout(this.scrollingFinishCB),this.scrollingFinishCB=
null;if(this.doScrollInterval)clearInterval(this.doScrollInterval),this.doScrollInterval=null;if(!(a.touches.length!=1||this.boolScrollLock)){if(a.touches[0].target&&a.touches[0].target.type!=void 0){var b=a.touches[0].target.tagName.toLowerCase();if(b=="select"||b=="input"||b=="button")return}b={top:0,left:0,speedY:0,speedX:0,absSpeedY:0,absSpeedX:0,deltaY:0,deltaX:0,absDeltaY:0,absDeltaX:0,y:0,x:0,duration:0};this.elementInfo={};var c=this.getViewportSize();this.elementInfo.bottomMargin=c.h;this.elementInfo.maxTop=
this.el.clientHeight-this.elementInfo.bottomMargin;if(this.elementInfo.maxTop<0)this.elementInfo.maxTop=0;this.elementInfo.divHeight=this.el.clientHeight;this.elementInfo.rightMargin=c.w;this.elementInfo.maxLeft=this.el.clientWidth-this.elementInfo.rightMargin;if(this.elementInfo.maxLeft<0)this.elementInfo.maxLeft=0;this.elementInfo.divWidth=this.el.clientWidth;this.elementInfo.hasVertScroll=this.verticalScroll||this.elementInfo.maxTop>0;this.elementInfo.hasHorScroll=this.elementInfo.maxLeft>0;this.elementInfo.requiresVScrollBar=
this.vscrollBar&&this.elementInfo.hasVertScroll;this.elementInfo.requiresHScrollBar=this.hscrollBar&&this.elementInfo.hasHorScroll;this.saveEventInfo(a);this.saveFirstEventInfo(a);a=this.getCSSMatrix(this.el);b.top=numOnly(a.f)-numOnly(this.container.scrollTop);b.left=numOnly(a.e)-numOnly(this.container.scrollLeft);this.container.scrollTop=this.container.scrollLeft=0;this.currentScrollingObject=this.el;if(this.refresh&&b.top==0)this.refreshHeight=this.refreshContainer.firstChild.clientHeight,this.refreshContainer.firstChild.style.top=
-this.refreshHeight+"px",this.refreshContainer.style.overflow="visible",this.preventPullToRefresh=!1;else if(b.top<0&&(this.preventPullToRefresh=!0,this.refresh))this.refreshContainer.style.overflow="hidden";b.x=b.left;b.y=b.top;if(this.setVScrollBar(b,0,0))this.container.clientWidth>window.innerWidth?this.vscrollBar.style.left=window.innerWidth-numOnly(this.vscrollBar.style.width)*3+"px":this.vscrollBar.style.right="0px",this.vscrollBar.style.webkitTransition="";if(this.setHScrollBar(b,0,0))this.container.clientHeight>
window.innerHeight?this.hscrollBar.style.top=window.innerHeight-numOnly(this.hscrollBar.style.height)+"px":this.hscrollBar.style.bottom=numOnly(this.hscrollBar.style.height),this.hscrollBar.style.webkitTransition="";this.lastScrollInfo=b;this.doScrollInterval&&window.clearInterval(this.doScrollInterval);this.doScrollInterval=null;var d=this;this.doScrollInterval=window.setInterval(function(){d.doScroll()},this.refreshRate)}}};d.prototype.getCSSMatrix=function(a){if(this.androidFormsMode){var b=parseInt(a.style.marginTop),
a=parseInt(a.style.marginLeft);isNaN(b)&&(b=0);isNaN(a)&&(a=0);return{f:b,e:a}}else{b=window.getComputedStyle(a).webkitTransform;if(b=="none")return{f:0,e:0};return new WebKitCSSMatrix(b)}};d.prototype.saveEventInfo=function(a){this.lastEventInfo={pageX:a.touches[0].pageX,pageY:a.touches[0].pageY,time:a.timeStamp}};d.prototype.saveFirstEventInfo=function(a){this.firstEventInfo={pageX:a.touches[0].pageX,pageY:a.touches[0].pageY,time:a.timeStamp}};d.prototype.setVScrollBar=function(a,b,c){if(!this.elementInfo.requiresVScrollBar)return!1;
var d=parseFloat(this.elementInfo.bottomMargin/this.elementInfo.divHeight)*this.elementInfo.bottomMargin+"px";if(d!=this.vscrollBar.style.height)this.vscrollBar.style.height=d;a=this.elementInfo.bottomMargin-numOnly(this.vscrollBar.style.height)-(this.elementInfo.maxTop+a.y)/this.elementInfo.maxTop*(this.elementInfo.bottomMargin-numOnly(this.vscrollBar.style.height));if(a>this.elementInfo.bottomMargin)a=this.elementInfo.bottomMargin;a<0&&(a=0);this.scrollbarMoveCSS(this.vscrollBar,{x:0,y:a},b,c);
return!0};d.prototype.setHScrollBar=function(a,b,c){if(!this.elementInfo.requiresHScrollBar)return!1;var d=parseFloat(this.elementInfo.rightMargin/this.elementInfo.divWidth)*this.elementInfo.rightMargin+"px";if(d!=this.hscrollBar.style.width)this.hscrollBar.style.width=d;a=this.elementInfo.rightMargin-numOnly(this.hscrollBar.style.width)-(this.elementInfo.maxLeft+a.x)/this.elementInfo.maxLeft*(this.elementInfo.rightMargin-numOnly(this.hscrollBar.style.width));if(a>this.elementInfo.rightMargin)a=this.elementInfo.rightMargin;
a<0&&(a=0);this.scrollbarMoveCSS(this.hscrollBar,{x:a,y:0},b,c);return!0};d.prototype.onTouchMove=function(a){if(this.currentScrollingObject!=null){var b=this.calculateMovement(a);this.calculateTarget(b);this.lastScrollInfo=b;this.moved=!0;this.saveEventInfo(a);if(this.elementInfo.requiresVScrollBar)this.vscrollBar.style.opacity=1;if(this.elementInfo.requiresHScrollBar)this.hscrollBar.style.opacity=1}};d.prototype.doScroll=function(){if(!this.isScrolling&&this.lastScrollInfo.x!=this.lastScrollInfo.left||
this.lastScrollInfo.y!=this.lastScrollInfo.top){this.isScrolling=!0;if(this.onScrollStart)this.onScrollStart();var a=this.getCSSMatrix(this.el);this.lastScrollInfo.top=numOnly(a.f);this.lastScrollInfo.left=numOnly(a.e);this.recalculateDeltaY(this.lastScrollInfo);this.recalculateDeltaX(this.lastScrollInfo);this.checkYboundary(this.lastScrollInfo);this.elementInfo.hasHorScroll&&this.checkXboundary(this.lastScrollInfo);var a=this.lastScrollInfo.y>0&&this.lastScrollInfo.deltaY>0,b=this.lastScrollInfo.y<
-this.elementInfo.maxTop&&this.lastScrollInfo.deltaY<0;if(a||b){var c=(this.container.clientHeight-(a?this.lastScrollInfo.y:-this.lastScrollInfo.y-this.elementInfo.maxTop))/this.container.clientHeight;c<0.5&&(c=0.5);var d=0;a&&this.lastScrollInfo.top>0||b&&this.lastScrollInfo.top<-this.elementInfo.maxTop?d=this.lastScrollInfo.top:b&&(d=-this.elementInfo.maxTop);b=this.lastScrollInfo.deltaY*c;Math.abs(this.lastScrollInfo.deltaY*c)<1&&(b=a?1:-1);this.lastScrollInfo.y=d+b}this.scrollerMoveCSS(this.lastScrollInfo,
0);this.setVScrollBar(this.lastScrollInfo,0,0);this.setHScrollBar(this.lastScrollInfo,0,0);if(this.refresh&&!this.preventPullToRefresh)if(!this.refreshTriggered&&this.lastScrollInfo.top>this.refreshHeight)this.refreshTriggered=!0,e.trigger(this,"refresh-trigger");else if(this.refreshTriggered&&this.lastScrollInfo.top<this.refreshHeight)this.refreshTriggered=!1,e.trigger(this,"refresh-cancel")}};d.prototype.calculateMovement=function(a,b){var c={top:0,left:0,speedY:0,speedX:0,absSpeedY:0,absSpeedX:0,
deltaY:0,deltaX:0,absDeltaY:0,absDeltaX:0,y:0,x:0,duration:0},d=b?this.firstEventInfo:this.lastEventInfo,e=b?a.pageX:a.touches[0].pageX,f=b?a.pageY:a.touches[0].pageY,g=b?a.time:a.timeStamp;c.deltaY=this.elementInfo.hasVertScroll?f-d.pageY:0;c.deltaX=this.elementInfo.hasHorScroll?e-d.pageX:0;c.time=g;c.duration=g-d.time;return c};d.prototype.calculateTarget=function(a){a.y=this.lastScrollInfo.y+a.deltaY;a.x=this.lastScrollInfo.x+a.deltaX};d.prototype.checkYboundary=function(a){var b=this.container.clientHeight/
2,c=this.elementInfo.maxTop+b;if(a.y>b)a.y=b;else if(-a.y>c)a.y=-c;else return;this.recalculateDeltaY(a)};d.prototype.checkXboundary=function(a){if(a.x>0)a.x=0;else if(-a.x>this.elementInfo.maxLeft)a.x=-this.elementInfo.maxLeft;else return;this.recalculateDeltaY(a)};d.prototype.recalculateDeltaY=function(a){var b=Math.abs(a.deltaY);a.deltaY=a.y-a.top;newAbsDeltaY=Math.abs(a.deltaY);a.duration=a.duration*newAbsDeltaY/b};d.prototype.recalculateDeltaX=function(a){var b=Math.abs(a.deltaX);a.deltaX=a.x-
a.left;newAbsDeltaX=Math.abs(a.deltaX);a.duration=a.duration*newAbsDeltaX/b};d.prototype.hideRefresh=function(){if(!this.preventHideRefresh)this.scrollerMoveCSS({x:0,y:0},75),this.refreshTriggered=!1};d.prototype.setMomentum=function(a){a.speedY=this.divide(a.deltaY,a.duration);a.speedX=this.divide(a.deltaX,a.duration);a.absSpeedY=Math.abs(a.speedY);a.absSpeedX=Math.abs(a.speedX);a.absDeltaY=Math.abs(a.deltaY);a.absDeltaX=Math.abs(a.deltaX);if(a.absDeltaY>0){if(a.deltaY=(a.deltaY<0?-1:1)*a.absSpeedY*
a.absSpeedY/0.0024,a.absDeltaY=Math.abs(a.deltaY),a.duration=a.absSpeedY/0.0012,a.speedY=a.deltaY/a.duration,a.absSpeedY=Math.abs(a.speedY),a.absSpeedY<0.12||a.absDeltaY<5)a.deltaY=a.absDeltaY=a.duration=a.speedY=a.absSpeedY=0}else if(a.absDeltaX){if(a.deltaX=(a.deltaX<0?-1:1)*a.absSpeedX*a.absSpeedX/0.0024,a.absDeltaX=Math.abs(a.deltaX),a.duration=a.absSpeedX/0.0012,a.speedX=a.deltaX/a.duration,a.absSpeedX=Math.abs(a.speedX),a.absSpeedX<0.12||a.absDeltaX<5)a.deltaX=a.absDeltaX=a.duration=a.speedX=
a.absSpeedX=0}else a.duration=0};d.prototype.onTouchEnd=function(){window.clearInterval(this.doScrollInterval);this.doScrollInterval=null;if(this.currentScrollingObject!=null&&this.moved){this.finishScrollingObject=this.currentScrollingObject;this.currentScrollingObject=null;var a=this.calculateMovement(this.lastEventInfo,!0);this.androidFormsMode||this.setMomentum(a);this.calculateTarget(a);var b=this.getCSSMatrix(this.el);a.top=numOnly(b.f);a.left=numOnly(b.e);this.checkYboundary(a);this.elementInfo.hasHorScroll&&
this.checkXboundary(a);b=!this.preventPullToRefresh&&(a.top>this.refreshHeight||a.y>this.refreshHeight);this.fireRefreshRelease(b,a.top>0);if(this.refresh&&b)a.y=this.refreshHeight,a.duration=75;else if(a.y>=0){if(a.y=0,a.top>=0)a.duration=75}else if(-a.y>this.elementInfo.maxTop||this.elementInfo.maxTop==0)if(a.y=-this.elementInfo.maxTop,-a.top>this.elementInfo.maxTop)a.duration=75;if(this.androidFormsMode)a.duration=0;this.scrollerMoveCSS(a,a.duration,"cubic-bezier(0.33,0.66,0.66,1)");this.setVScrollBar(a,
a.duration,"cubic-bezier(0.33,0.66,0.66,1)");this.setHScrollBar(a,a.duration,"cubic-bezier(0.33,0.66,0.66,1)");this.setFinishCalback(a.duration)}};d.prototype.setFinishCalback=function(a){var b=this;this.scrollingFinishCB=setTimeout(function(){b.hideScrollbars();e.trigger(e.touchLayer,"scrollend",[b.el]);b.isScrolling=!1;b.elementInfo=null},a)};d.prototype.startFormsMode=function(){if(!this.blockFormsFix){var a=this.getCSSMatrix(this.el);this.refreshSafeKeep=this.refresh;this.refresh=!1;this.androidFormsMode=
!0;this.el.style.webkitTransform="none";this.el.style.webkitTransition="none";this.el.style.webkitPerspective="none";this.scrollerMoveCSS({x:numOnly(a.e),y:numOnly(a.f)},0);this.container.style.webkitPerspective="none";this.container.style.webkitBackfaceVisibility="visible";if(this.vscrollBar)this.vscrollBar.style.webkitTransform="none",this.vscrollBar.style.webkitTransition="none",this.vscrollBar.style.webkitPerspective="none",this.vscrollBar.style.webkitBackfaceVisibility="visible";if(this.hscrollBar)this.hscrollBar.style.webkitTransform=
"none",this.hscrollBar.style.webkitTransition="none",this.hscrollBar.style.webkitPerspective="none",this.hscrollBar.style.webkitBackfaceVisibility="visible"}};d.prototype.stopFormsMode=function(){if(!this.blockFormsFix){var a=this.getCSSMatrix(this.el);this.refresh=this.refreshSafeKeep;this.androidFormsMode=!1;this.el.style.webkitPerspective=1E3;this.el.style.marginTop=0;this.el.style.marginLeft=0;this.el.style.webkitTransition="0ms linear";this.scrollerMoveCSS({x:numOnly(a.e),y:numOnly(a.f)},0);
this.container.style.webkitPerspective=1E3;this.container.style.webkitBackfaceVisibility="hidden";if(this.vscrollBar)this.vscrollBar.style.webkitPerspective=1E3,this.vscrollBar.style.webkitBackfaceVisibility="hidden";if(this.hscrollBar)this.hscrollBar.style.webkitPerspective=1E3,this.hscrollBar.style.webkitBackfaceVisibility="hidden"}};d.prototype.scrollerMoveCSS=function(a,b,c){b||(b=0);c||(c="linear");if(this.el&&this.el.style){if(this.eventsActive)this.androidFormsMode?(this.el.style.marginTop=
Math.round(a.y)+"px",this.el.style.marginLeft=Math.round(a.x)+"px"):(this.el.style.webkitTransform="translate"+k+a.x+"px,"+a.y+"px"+l,this.el.style.webkitTransitionDuration=b+"ms",this.el.style.webkitTransitionTimingFunction=c);this.logPos(a.x,a.y)}};d.prototype.logPos=function(a,b){var c=this.elementInfo?{h:this.elementInfo.bottomMargin,w:this.elementInfo.rightMargin}:this.getViewportSize();this.loggedPcentX=this.divide(a,this.el.clientWidth-c.w);this.loggedPcentY=this.divide(b,this.el.clientHeight-
c.h);this.scrollTop=b;this.scrollLeft=a};d.prototype.scrollbarMoveCSS=function(a,b,c,d){c||(c=0);d||(d="linear");if(a&&a.style)this.androidFormsMode?(a.style.marginTop=Math.round(b.y)+"px",a.style.marginLeft=Math.round(b.x)+"px"):(a.style.webkitTransform="translate"+k+b.x+"px,"+b.y+"px"+l,a.style.webkitTransitionDuration=c+"ms",a.style.webkitTransitionTimingFunction=d)};d.prototype.scrollTo=function(a,b){b||(b=0);this.scrollerMoveCSS(a,b)};d.prototype.scrollBy=function(a,b){var c=this.getCSSMatrix(this.el),
d=numOnly(c.f),c=numOnly(c.e);this.scrollTo({y:d-a.y,x:c-a.x},b)};return function(a,b){!n&&e.touchLayer&&e.isObject(e.touchLayer)&&o();var c=typeof a=="string"||a instanceof String?document.getElementById(a):a;if(c){if(b.useJsScroll)return new d(c,b);return new f(c,b)}else alert("Could not find element for scroller "+a)}}}()})(jq);
(function(e){e.availableTransitions.fade=function(a,b,f){a.style.display="block";b.style.display="block";var c=this;f?(b.style.zIndex=1,a.style.zIndex=2,c.clearAnimations(b),c.css3animate(a,{x:"0%",time:"150ms",opacity:0.1,complete:function(d){d?c.finishTransition(a,b):(c.css3animate(a,{x:"-100%",opacity:1,complete:function(){c.finishTransition(a)}}),b.style.zIndex=2,a.style.zIndex=1)}})):(a.style.zIndex=1,b.style.zIndex=2,b.style.opacity=0,c.css3animate(b,{x:"0%",opacity:0.1,complete:function(){c.css3animate(b,
{x:"0%",time:"150ms",opacity:1,complete:function(d){d?c.finishTransition(a,b):(c.clearAnimations(b),c.css3animate(a,{x:"-100%",y:0,complete:function(){c.finishTransition(a)}}))}})}}))}})($.ui);
(function(e){e.availableTransitions.flip=function(a,b,f){a.style.display="block";b.style.display="block";var c=this;f?(c.css3animate(b,{x:"100%",scale:0.8,rotateY:"180deg",complete:function(){c.css3animate(b,{x:"0%",scale:1,time:"150ms",rotateY:"0deg",complete:function(){c.clearAnimations(b)}})}}),c.css3animate(a,{x:"100%",time:"150ms",scale:0.8,rotateY:"180deg",complete:function(){c.css3animate(a,{x:"-100%",opacity:1,scale:1,rotateY:"0deg",complete:function(){c.finishTransition(a)}});b.style.zIndex=
2;a.style.zIndex=1}})):(a.style.zIndex=1,b.style.zIndex=2,c.css3animate(a,{x:"100%",time:"150ms",scale:0.8,rotateY:"180deg",complete:function(){c.css3animate(a,{x:"-100%",y:0,time:"1ms",scale:1,rotateY:"0deg",complete:function(){c.finishTransition(a)}})}}),c.css3animate(b,{x:"100%",time:"1ms",scale:0.8,rotateY:"180deg",complete:function(){c.css3animate(b,{x:"0%",time:"150ms",scale:1,rotateY:"0deg",complete:function(){c.clearAnimations(b)}})}}))}})($.ui);
(function(e){e.availableTransitions.pop=function(a,b,f){a.style.display="block";b.style.display="block";var c=this;f?(b.style.zIndex=1,a.style.zIndex=2,c.clearAnimations(b),c.css3animate(a,{x:"0%",time:"150ms",opacity:0.1,scale:0.2,origin:"-50% 50%",complete:function(d){d?c.finishTransition(a):(c.css3animate(a,{x:"-100%",complete:function(){c.finishTransition(a)}}),b.style.zIndex=2,a.style.zIndex=1)}})):(a.style.zIndex=1,b.style.zIndex=2,c.css3animate(b,{x:"0%",y:"0%",scale:0.2,origin:"-50% 50%",
opacity:0.1,complete:function(){c.css3animate(b,{x:"0%",time:"150ms",scale:1,opacity:1,origin:"0% 0%",complete:function(d){d?c.finishTransition(a,b):(c.clearAnimations(b),c.css3animate(a,{x:"100%",y:0,complete:function(){c.finishTransition(a)}}))}})}}))}})($.ui);
(function(e){function a(b,a,c){b.style.display="block";a.style.display="block";var d=this;c?d.css3animate(b,{x:"0%",y:"0%",complete:function(){d.css3animate(b,{x:"100%",time:"150ms",complete:function(){d.finishTransition(b,a)}}).link(a,{x:"0%",time:"150ms"})}}).link(a,{x:"-100%",y:"0%"}):d.css3animate(b,{x:"0%",y:"0%",complete:function(){d.css3animate(b,{x:"-100%",time:"150ms",complete:function(){d.finishTransition(b,a)}}).link(a,{x:"0%",time:"150ms"})}}).link(a,{x:"100%",y:"0%"})}e.availableTransitions.slide=
a;e.availableTransitions["default"]=a})($.ui);
(function(e){e.availableTransitions.down=function(a,b,e){a.style.display="block";b.style.display="block";var c=this;e?(b.style.zIndex=1,a.style.zIndex=2,c.clearAnimations(b),c.css3animate(a,{y:"-100%",x:"0%",time:"150ms",complete:function(d){d?c.finishTransition(a,b):(c.css3animate(a,{x:"-100%",y:0,complete:function(){c.finishTransition(a)}}),b.style.zIndex=2,a.style.zIndex=1)}})):(a.style.zIndex=1,b.style.zIndex=2,c.css3animate(b,{y:"-100%",x:"0%",complete:function(){c.css3animate(b,{y:"0%",x:"0%",
time:"150ms",complete:function(d){d?c.finishTransition(a,b):(c.clearAnimations(b),c.css3animate(a,{x:"-100%",y:0,complete:function(){c.finishTransition(a)}}))}})}}))}})($.ui);
(function(e){e.availableTransitions.up=function(a,b,e){a.style.display="block";b.style.display="block";var c=this;e?(b.style.zIndex=1,a.style.zIndex=2,c.clearAnimations(b),c.css3animate(a,{y:"100%",x:"0%",time:"150ms",complete:function(){c.finishTransition(a);b.style.zIndex=2;a.style.zIndex=1}})):(b.style.zIndex=2,a.style.zIndex=1,c.css3animate(b,{y:"100%",x:"0%",complete:function(){c.css3animate(b,{y:"0%",x:"0%",time:"150ms",complete:function(d){d?c.finishTransition(a,b):(c.clearAnimations(b),c.css3animate(a,
{x:"-100%",y:0,complete:function(){c.finishTransition(a)}}))}})}}))}})($.ui);
   